name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
          matrix:
            node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: location 
        run: pwd && ls 

      - name: Install modules
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist
          commit-message: 'Actualización de despliegue :D'
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
